apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aprf-workloads-root
  namespace: openshift-gitops-apps
spec:
  project: aprf-workloads
  source:
    repoURL: https://github.com/example/aprf-runtime-gitops.git
    targetRevision: aprf-live
    path: kustomize/profiles/article-default
  destination:
    server: https://kubernetes.default.svc
    namespace: basic-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jqPathExpressions:
        - .spec.template.spec.containers[]?.image
