apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "63400"
  labels:
    app.kubernetes.io/name: catalog-jvm
  name: catalog-jvm
spec:
  selector:
    app.kubernetes.io/name: catalog-jvm
  ports:
    - name: http
      port: 8080
      targetPort: http
