apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "64100"
  name: experience-jvm-config
data:
  CATALOG_MP_REST_URL: "http://catalog-jvm.catalog-jvm.svc.cluster.local:8080"
