apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "64000"
  name: experience-jvm
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: TEST_01/experience-jvm:TEST_02
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Local
