apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "64300"
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"experience-native:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"experience-native\")].image"}]
  name: experience-native
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: experience-native
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: experience-native
    spec:
      terminationGracePeriodSeconds: 30
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: experience-native
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: experience-native
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
      containers:
        - name: experience-native
          image: experience-native:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: experience-native-config
          ports:
            - containerPort: 8080
              name: http
          startupProbe:
            failureThreshold: 12
            httpGet:
              path: /q/health/ready
              port: http
            periodSeconds: 5
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /q/health/ready
              port: http
            periodSeconds: 10
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: http
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 750m
              memory: 320Mi
