apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "64350"
  name: experience-native
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: experience-native
