apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "64400"
  labels:
    app.kubernetes.io/name: experience-native
  name: experience-native
spec:
  selector:
    app.kubernetes.io/name: experience-native
  ports:
    - name: http
      port: 8080
      targetPort: http
